#ifndef MPE_UTILS_H
#define  MPE_UTILS_H

// -----------SEND----------- //
#define START_SEND_COLUMN_SIZE 10
#define END_SEND_COLUMN_SIZE 11

#define START_SEND_COLUMN_VALUES 12
#define END_SEND_COLUMN_VALUES 13

#define START_SEND_COLUMN_ID 14
#define END_SEND_COLUMN_ID 15

#define START_SEND_DIMENSIONS_ROWS_SIZE 16
#define END_SEND_DIMENSIONS_ROWS_SIZE 17

#define START_SEND_DIMENSIONS_COLS_SIZE 18
#define END_SEND_DIMENSIONS_COLS_SIZE 19

// -----------RECV----------- //
#define START_RECV_COLUMN_SIZE 20
#define END_RECV_COLUMN_SIZE 21

#define START_RECV_COLUMN_VALUES 22
#define END_RECV_COLUMN_VALUES 23

#define START_RECV_COLUMN_ID 24
#define END_RECV_COLUMN_ID 25

#define START_RECV_DIMENSIONS_ROWS_SIZE 26
#define END_RECV_DIMENSIONS_ROWS_SIZE 27

#define START_RECV_DIMENSIONS_COLS_SIZE 28
#define END_RECV_DIMENSIONS_COLS_SIZE 29

#endif /*MPE_UTILS_H*/
